CREATE TABLE IF NOT EXISTS vehicle (
  id VARCHAR NOT NULL,
  user_id VARCHAR NOT NULL,
  type VARCHAR NOT NULL  DEFAULT '',
  brand VARCHAR NOT NULL DEFAULT '',
  number VARCHAR  NOT NULL, 
  region  INTEGER NOT NULL DEFAULT 0,
  country VARCHAR NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ  NOT NULL DEFAULT (now()),
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
