// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CountVehicleByNumber(ctx context.Context, number string) (int64, error)
	CountVehicleByRegion(ctx context.Context, arg CountVehicleByRegionParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	DeleteVehicle(ctx context.Context, arg DeleteVehicleParams) error
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetVehicleByID(ctx context.Context, arg GetVehicleByIDParams) (Vehicle, error)
	GetVehicleByNumber(ctx context.Context, arg GetVehicleByNumberParams) ([]Vehicle, error)
	GetVehicleByRegion(ctx context.Context, arg GetVehicleByRegionParams) ([]Vehicle, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error)
}

var _ Querier = (*Queries)(nil)
